### PR TITLE
[Picker] increase picker visual feedback for kids.

### PR DESCRIPTION
**Pull request by tbarthel-fr**
Color the action bar in addition of the picker crosshair.

### CODE REVIEW

**Comment by tbarthel-fr** [comment]
device-2017-05-06-175344

**Comment by vbarthel-fr** [comment]
lgtm 🐪

**Review by jo-elimu — APPROVED** [review]
Is the color changing gradually?

**Comment by tbarthel-fr** [comment]
The behavior is the same as the actual crosshair. Both colors are going to be the same and will change "live" based on each camera frame.

**Pull request merged**
