### PR TITLE
[Tabs] replace text by icons for kids.

### PR DESCRIPTION
**Pull request by tbarthel-fr**
Fab button as been changed to a '+' icon for not using
same icons at different place. In addition, it could
help to understand the action behind the FAB.

for kids : 
icons

default : 

text

### CODE REVIEW

**Comment by vbarthel-fr** [comment]
lgtm :+1:

**Comment by tbarthel-fr** [comment]
adult version : keep icons instead of + icons.

**Comment by jo-elimu** [comment]
@tbarthel-fr Actually, kid's who have not learned literacy/numeracy yet do not know what '+' means, so icons should be of shapes/figures rather than characters.

**Comment by vbarthel-fr** [comment]
Make sense, thanks for the clarification =)

@tbarthel-fr Do you think we could re-use the "drop" allusion you used in  #15. One drop for picking a color,  3 "merging drops" for creating a palette?

**Comment by tbarthel-fr** [comment]
@jogrimst thanks for this precious feedback! We are going to rework this icon asap (=

**Comment by tbarthel-fr** [comment]
@jogrimst Here is another attempt to replace text used as tab title by icons.

This time, original FAB icons as been kept since their represent the best which action is behind. And we simply use shapes to replace tab title. 

device-2016-07-25-122027

device-2016-07-25-122056

device-2016-07-25-122254

device-2016-07-25-122642

**Comment by jo-elimu** [comment]
@tbarthel-fr I think the circle vs square is a good solution. Maybe the square could be replaced with the "view_column" icon also? https://github.com/google/material-design-icons/blob/master/action/2x_web/ic_view_column_black_48dp.png

**Comment by jo-elimu** [comment]
@tbarthel-fr I just tested the app on a Google Pixel C device. And it was difficult to see the white color, both in the "selected colors" tab, and in the activity for creating a new palette. Maybe the white color should behave slightly different? Or put some mild shadow behind each circle?

screenshot_20160727-131833

**Comment by tbarthel-fr** [comment]
Hi @jogrimst (=

Ok for the shape! Here is a screenshot with the column icon you suggested. I let you choose between square and column before submitting it for review (:

device-2016-07-28-082241

Regarding the white color, we definitely have to find a trick for every color close enough to the background one (x we will come back to you with a proposition as soon as we would have one (: (probably some kinds of shadow). I'm going to create an issue to track this down.

Regarding the tablette support, we are going to submit you some small changes which must improve the user experience on 9' and 10' devices. Basically, most of this small changes are going to be dimen tweaks. A new PR will be created soon.

Best regards,

Thomas.

**Comment by jo-elimu** [comment]
> Ok for the shape! Here is a screenshot with the column icon you suggested. I let you choose between square and column before submitting it for review (:

@tbarthel-fr Thanks. I think the column variant looks a bit better than the square for the icon.

**Comment by tbarthel-fr** [comment]
@jogrimst Perfect (= I mark this feature as validated and wait for @vbarthel-fr review!

**Comment by vbarthel-fr** [comment]
@tbarthel-fr the solution adopted does not seem to use the `ic_add` drawable: the resource is unused.

Otherwise, lgtm :+1:

**Pull request merged**
