### PR TITLE
[Capture] restore picked color animation.

### PR DESCRIPTION
**Pull request by tbarthel-fr**
Behaviour was broken on tablet since target isn't
in the bottom left corner anymore.

### CODE REVIEW

**Comment by jo-elimu** [comment]
@tbarthel-fr Could you send me the latest APK file so that I can test on the Pixel C tablet?

**Comment by tbarthel-fr** [comment]
@jogrimst sure, I have just send you an email with an apk including every pending tweaks (=

**Comment by jo-elimu** [comment]
@tbarthel-fr Thanks, just tested it. Looks great 👍 

Could you also make it possible to use the app while holding the tablet upside down in horizontal mode?

**Comment by vbarthel-fr** [comment]
lgtm :octopus:

**Pull request merged**
