### PR TITLE
implement org.openintents.action.PICK_COLOR

### PR DESCRIPTION
**Pull request by travisfw**
I was looking for a color picker in F-Droid for an app I'm writing, and it would be perfect to use CameraColorPicker, so I implemented the OpenIntents PICK_COLOR action for the ColorPickerActivity. Hopefully this can be useful to others as well.

http://www.openintents.org/action/org-openintents-action-pick-color/

### CODE REVIEW

**Comment by tbarthel-fr** [comment]
Hi @travisfw (=

Thanks a lot for your interest in this project!

It will be an awesome feature (: Could you squash your two commits so that we could merge your work?

**Comment by travisfw** [comment]
Okay @tbarthel-fr how's that look?

**Comment by tbarthel-fr** [comment]
LGTM 🐨

**Comment by vbarthel-fr** [comment]
@travisfw wow great work! Did not know about the open-intents, sounds promissing =)

**Comment by vbarthel-fr** [comment]
lgtm 🌔

**Pull request merged**
