### PR TITLE
[Palette list] Adapt the palette list to the kids/adult falvors.

### PR DESCRIPTION
**Pull request by vbarthel-fr**
This MR adapt the palette list for kids.

In the kids version of the app, the palettes are now displayed in a grid. The names of the palette are no longer shown.

Here is a screenshot of the default version:
device-2016-07-24-150847

Here is a screenshot of the kids version:
device-2016-07-24-150915

@tbarthel-fr Compared to my last MR for the color items, I managed to share more code between product flavors. If this is OK for you, I will probably factorize the code for the color items =)

### CODE REVIEW

**Comment by jo-elimu** [comment]
By the way, when the palette list is empty, it says "To add colors to your palette simply click on the list below."

**Comment by vbarthel-fr** [comment]
@jogrimst You have just merged an MR that was in the review process (labelled 'to-review' and assigned to Thomas).  I don't know if Thomas has explained you how we would like to work on this project, but here is a short summary:

For consistency accross the project, for keeping a global vison of the project, and for double checking code for bugs, the MRs are always reviewed by another peer. The submitter lables the MR with 'to-review' and assigns another member to review his/her work. When the assignee is done, he/she labels the MR with 'reviewed' and assigns the original submitter. 

When the code has been properly reviewed, we include you in the loop with the label 'to-validate'. You can then make us your comments/remarks. When you are satisfied with the feature, you should label the MR with 'validated' and assignes the original submitter.

At that point the MR has been reviewed by another developer and validated by you, it should have two labels 'reviewed' and 'validated'. And should be assigned to the original submitter.

The original submitter can now check if there are no merge conflicts with the base and merge!

It might seems a little bit overkilled for such a project, but we hope that it will help us keep this project in good shape and well organized =)

That being said, this flow is certainly not written in stone: please do not hesitate to tell us if you would like to use another work-flow :)

**Comment by jo-elimu** [comment]
@vbarthel-fr Thanks for clarifying :-)

I think it's great that you are doing it this way, even for a small project. Such a work-flow keeps the quality high.

A question: Is there any way to test the changes in a pull request on an Android device _before_ it's merged into the branch? It can sometimes be difficult to know how animations work just by looking at code changes without actually navigating the interface.

**Comment by vbarthel-fr** [comment]
@jogrimst You can checkout the source branch and build the project from that branch. In this case, you could have pulled he branch `vb/palette-list` to test the new palette list =)

@tbarthel-fr I am going to delete the source branch of this MR and mark it as "reviewed" and "validated". If you find something that requires a fix or a modification, please open an issue and assign me =)

**Pull request merged**
