### PR TITLE
[Color items] Adapts the color item list to the kids/adult flavors.

### PR DESCRIPTION
**Pull request by vbarthel-fr**
This MR is an attempt to adapt the color item lists for kids.

In the kids version of the app, the color items are now displayed as a grid. The hexadecimal codes are no longer shown. And long press actions for copying the hexa codes to the clip board has been disabled.

Here are some screenshots of the default version:
device-2016-07-24-111220
device-2016-07-24-111301

And here are some screenshots of the kids version:
device-2016-07-24-111332
device-2016-07-24-111406

Once this MR is validated, I will adapt the palette lists in the same way =)

### CODE REVIEW

**Comment by jo-elimu** [comment]
Looks great :-)

Would it be possible to remove the text "New palette" from the ActionBar also?

**Comment by vbarthel-fr** [comment]
Absolutely, but this will be part of another MR =) This MR only focus on the color item lists. 

We split the work into small MR so that it is easier for us to divide the tasks and for you to see what changes =)

**Comment by tbarthel-fr** [comment]
lgtm 👾

**Comment by jo-elimu** [comment]
@vbarthel-fr Ok, good strategy :-)

I think the new item list looks very intuitive.

**Pull request merged**
